# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awscredentialmgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('current_version', models.CharField(max_length=500)),
                ('previous_version', models.CharField(max_length=500)),
                ('instance_count', models.IntegerField()),
                ('configuration', models.TextField()),
                ('load_balancer_names', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awscredentialmgr.AWSProfile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awscredentialmgr.AWSRegion')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_code', models.CharField(max_length=500)),
                ('project_leader', models.CharField(max_length=500)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updateplanmgr.Module')),
                ('previous_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='updateplanmgr.Module')),
            ],
        ),
        migrations.AddField(
            model_name='updateplan',
            name='steps',
            field=models.ManyToManyField(to='updateplanmgr.UpdateStep'),
        ),
    ]
