# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_online_version',
            field=models.BooleanField(default=False),
        ),
    ]
