# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0002_module_is_online_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatestep',
            old_name='order',
            new_name='sequence',
        ),
    ]
