# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0003_auto_20170104_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatestep',
            name='previous_module',
        ),
    ]
