# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0006_auto_20170104_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatestep',
            name='ec2_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatestep',
            name='elb_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updateplan',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 4, 8, 43, 7, 916000, tzinfo=utc)),
        ),
    ]
