# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ec2mgr', '0001_initial'),
        ('updateplanmgr', '0007_auto_20170104_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='instances',
            field=models.ManyToManyField(to='ec2mgr.EC2Instance'),
        ),
        migrations.AlterField(
            model_name='updateplan',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
