# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0008_auto_20170106_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='service_type',
            field=models.CharField(default=b'java', max_length=500),
        ),
    ]
