# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0010_updateactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateactionlog',
            name='update_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updateplanmgr.UpdatePlan'),
        ),
        migrations.AlterField(
            model_name='updateactionlog',
            name='update_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updateplanmgr.UpdateStep'),
        ),
    ]
