# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0013_auto_20170721_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateplan',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='instances',
            field=models.ManyToManyField(blank=True, null=True, related_name='modules', to='ec2mgr.EC2Instance'),
        ),
    ]
