# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0014_auto_20180927_0939'),
        ('updateplanmgr', '0014_auto_20181122_1121'),
    ]

    operations = [
    ]
