# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateplanmgr', '0015_merge_20181122_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='instances',
            field=models.ManyToManyField(blank=True, related_name='modules', to='ec2mgr.EC2Instance'),
        ),
    ]
