# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('instance_id', models.CharField(max_length=500)),
                ('private_ip_address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('key_pair', models.CharField(max_length=100)),
                ('running_state', models.CharField(max_length=100)),
                ('service_status', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
