# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2mgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='username',
            field=models.CharField(default=b'ubuntu', max_length=100),
        ),
    ]
