# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ec2mgr', '0003_auto_20170109_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
