# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2mgr', '0004_auto_20170113_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
