# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2mgr', '0006_ec2instance_vpc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='service_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
