# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('aws_access_key_id', models.CharField(default=b'', max_length=500)),
                ('aws_secret_access_key', models.CharField(default=b'', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AWSRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.CharField(max_length=500)),
                ('tag_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='awsprofile',
            name='regions',
            field=models.ManyToManyField(to='awscredentialmgr.AWSRegion'),
        ),
    ]
