# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awscredentialmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsprofile',
            name='account_id',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
