# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awscredentialmgr', '0002_awsprofile_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsprofile',
            name='aws_access_key_id',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='awsprofile',
            name='aws_secret_access_key',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
    ]
