# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awscredentialmgr', '0003_auto_20170227_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsprofile',
            name='regions',
            field=models.ManyToManyField(related_name='profiles', to='awscredentialmgr.AWSRegion'),
        ),
    ]
