# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awscredentialmgr', '0004_auto_20170407_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsprofile',
            name='service_dir_prefix',
            field=models.CharField(blank=True, default=b'cloud', max_length=500),
        ),
    ]
