# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awscredentialmgr', '0002_awsprofile_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('resource_id', models.CharField(max_length=500)),
                ('resource_type', models.CharField(max_length=100)),
                ('arn', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='awsresourcemgr.AWSResource')),
                ('profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='awscredentialmgr.AWSProfile')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='awscredentialmgr.AWSRegion')),
            ],
        ),
    ]
